const KEY='englishLabV2';
const defaultState={journals:[],quizHistory:[],mistakes:[],learnedWords:[],studyDays:[],builderDone:0,settings:{provider:'OpenAI',endpoint:'http://localhost:3000/api/chat'}};
const lessons=[
{id:'server',title:'A Day in the Life of a Server Engineer',level:'Beginner',profession:'Technology',story:'A server engineer starts the day by checking messages and system alerts. They review server health, inspect logs, monitor networks, solve incidents and document changes before ending the day.',vocab:[['monitor','to watch a system carefully'],['alert','a warning about a problem'],['log','a record of system activity'],['deploy','to release software'],['incident','an unexpected technical problem'],['backup','a copy kept for recovery'],['network','systems that connect computers'],['troubleshoot','to find and fix a problem']],sentences:['I check the server every morning.','I review the logs before I deploy a change.','The network is stable today.','I troubleshoot the incident with my team.','I document every important change.'],questions:[['What does an alert give you?',['A warning','A meal','A password'],'A warning'],['Choose the natural sentence.',['I check server every morning.','I check the server every morning.','I checking server morning.'],'I check the server every morning.']]},
{id:'farmer',title:'A Day in the Life of a Farmer',level:'Beginner',profession:'Agriculture',story:'A farmer wakes early, checks the weather, feeds animals, waters crops, works in the field, repairs tools, sells produce and prepares for the next morning.',vocab:[['crop','a plant grown for food'],['harvest','to collect mature crops'],['field','land used for farming'],['soil','earth where plants grow'],['feed','to give food to animals'],['irrigate','to supply water to crops'],['tool','an object used for work'],['market','a place where goods are sold']],sentences:['I wake up before sunrise.','I check the soil before I water the crops.','We harvest the vegetables in the afternoon.','I take the produce to the market.','I prepare my tools for tomorrow.'],questions:[['When does the farmer wake up?',['Before sunrise','At noon','At midnight'],'Before sunrise'],['What is a field?',['Land used for farming','A computer','A shop'],'Land used for farming']]},
{id:'fisherman',title:'A Day in the Life of a Fisherman',level:'Beginner',profession:'Fishing',story:'A fisherman prepares the boat and equipment, checks the weather and goes out on the water. During the day they catch fish, return to shore, sort the catch and sell it.',vocab:[['boat','a small vessel for water'],['net','material used to catch fish'],['shore','land beside water'],['catch','fish or other animals caught'],['tide','the rise and fall of sea level'],['weather','conditions in the air'],['equipment','tools needed for an activity'],['sort','to separate into groups']],sentences:['I check the weather before I leave.','We prepare the nets early in the morning.','The tide is changing.','We return to shore before dark.','I sort the fish after we arrive.'],questions:[['What does a fisherman prepare?',['Nets and equipment','Homework','A classroom'],'Nets and equipment'],['Where do they return?',['To shore','To school','To a factory'],'To shore']]},
{id:'teacher',title:'A Day in the Life of a Teacher',level:'Beginner',profession:'Education',story:'A teacher wakes up, prepares lessons, travels to school, teaches classes, checks student work, answers questions and plans the next day.',vocab:[['lesson','a period of teaching'],['assignment','work given to a student'],['explain','to make something clear'],['grade','a mark showing performance'],['classroom','a room for teaching'],['prepare','to get ready'],['student','a person who learns'],['feedback','advice about performance']],sentences:['I prepare my lesson before class.','I explain the topic with examples.','I check the students’ assignments.','I give useful feedback.','I plan tomorrow’s lesson at night.'],questions:[['What does a teacher prepare?',['A lesson','A boat','A fishing net'],'A lesson'],['What is feedback?',['Advice about performance','A meal','A vehicle'],'Advice about performance']]},
{id:'doctor',title:'A Day in the Life of a Doctor',level:'Beginner',profession:'Healthcare',story:'A doctor reviews appointments, meets patients, asks questions, examines symptoms, explains treatment and records important information.',vocab:[['patient','a person receiving medical care'],['symptom','a sign of an illness'],['treatment','medical care for a condition'],['appointment','a planned meeting'],['examine','to look at carefully'],['record','written information'],['advice','a recommendation'],['clinic','a place for medical care']],sentences:['I review my appointments in the morning.','I ask the patient about the symptoms.','I explain the treatment clearly.','I record important information.','I give the patient practical advice.'],questions:[['Who receives medical care?',['A patient','A farmer','A driver'],'A patient'],['What does a doctor review?',['Appointments','Fishing nets','Crops'],'Appointments']]},
{id:'driver',title:'A Day in the Life of a Driver',level:'Beginner',profession:'Transport',story:'A driver checks the vehicle, plans the route, starts the trip, follows traffic rules, communicates with customers and finishes the day by checking the vehicle again.',vocab:[['route','the way from one place to another'],['vehicle','a machine used for transport'],['traffic','vehicles on roads'],['fuel','energy used by an engine'],['deliver','to take something to a place'],['passenger','a person travelling in a vehicle'],['brake','a device for slowing a vehicle'],['schedule','a plan of times']],sentences:['I check the vehicle before I start.','I plan the route before the trip.','I follow the traffic rules.','I deliver the package on time.','I check the brakes at the end of the day.'],questions:[['What does a driver plan?',['A route','A lesson','A harvest'],'A route'],['What does fuel provide?',['Energy for an engine','Feedback','A classroom'],'Energy for an engine']]},
{id:'shopkeeper',title:'A Day in the Life of a Shopkeeper',level:'Beginner',profession:'Business',story:'A shopkeeper opens the store, checks stock, arranges products, helps customers, records sales, receives deliveries and closes the shop.',vocab:[['stock','goods available for sale'],['customer','a person buying something'],['price','how much something costs'],['sale','an exchange for money'],['supplier','a person or company providing goods'],['receipt','proof of purchase'],['arrange','to put in order'],['deliver','to bring goods to a place']],sentences:['I open the shop at eight.','I check the stock before customers arrive.','I help customers choose products.','I record every sale.','I close the shop at night.'],questions:[['What does a shopkeeper check?',['Stock','Tides','Lessons'],'Stock'],['Who buys something?',['A customer','A supplier','A teacher'],'A customer']]},
{id:'designer',title:'A Day in the Life of a Designer',level:'Beginner',profession:'Creative Work',story:'A designer checks messages, reviews a brief, sketches ideas, creates drafts, gets feedback, revises the design and prepares the final files.',vocab:[['brief','a short description of a project'],['draft','an early version'],['feedback','comments for improvement'],['revise','to change and improve'],['layout','the arrangement of elements'],['client','a person or company receiving a service'],['concept','an idea for a design'],['final','the completed version']],sentences:['I read the project brief in the morning.','I create a first draft.','I ask the client for feedback.','I revise the layout.','I export the final files.'],questions:[['What is a draft?',['An early version','A final bill','A vehicle'],'An early version'],['What does a designer request?',['Feedback','Fuel','Tide'],'Feedback']]}
];
function state(){return JSON.parse(localStorage.getItem(KEY)||JSON.stringify(defaultState))}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function today(){return new Date().toISOString().slice(0,10)}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderHome(){const s=state(); document.getElementById('today').textContent=today(); document.getElementById('vocab').textContent=s.learnedWords.length; document.getElementById('progress').textContent=Math.min(30,s.studyDays.length)+'%'; document.getElementById('streak').textContent=calcStreak(s.studyDays)+' days'; document.getElementById('professions').innerHTML=lessons.slice(0,6).map(l=>`<div class="card"><small>${l.profession}</small><h3>${l.title}</h3><p class="muted">${l.story.slice(0,110)}…</p><a class="btn" href="learn.html?lesson=${l.id}">Learn</a></div>`).join('')}
function calcStreak(days){let d=new Date(), n=0; while(days.includes(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)} return n}
function initLearn(){const sel=document.getElementById('profession'); sel.innerHTML=lessons.map(l=>`<option value="${l.id}">${l.title}</option>`).join(''); const id=new URLSearchParams(location.search).get('lesson'); if(id)sel.value=id; sel.onchange=()=>showLesson(sel.value); showLesson(sel.value); window.builder={i:0}}
function showLesson(id){const l=lessons.find(x=>x.id===id)||lessons[0]; document.getElementById('lesson').innerHTML=`<div class="lesson-hero"><p class="eyebrow">${l.profession} · ${l.level}</p><h1>${l.title}</h1><p class="muted">${l.story}</p><h2>Useful vocabulary</h2><div class="vocab">${l.vocab.map(v=>`<span class="pill"><b>${v[0]}</b> — ${v[1]}</span>`).join('')}</div><h2>Useful sentences</h2>${l.sentences.map(x=>`<div class="card">${x}</div>`).join('')}</div>`; builderData=l.sentences; window.builder.i=0; updateBuilder()}
let builderData=[]; function updateBuilder(){const i=window.builder?.i||0; if(!builderData.length)return; document.getElementById('builderStep').textContent=`${i+1}/${builderData.length}`; const target=builderData[i]; document.getElementById('builderPrompt').textContent='Build this sentence: '+target; const words=target.replace(/[.?!]/g,'').split(' ').sort(()=>Math.random()-.5); document.getElementById('builderWords').innerHTML=words.map(w=>`<span class="word" onclick="addWord('${esc(w)}')">${esc(w)}</span>`).join(''); document.getElementById('builderAnswer').textContent=''}
function addWord(w){document.getElementById('builderAnswer').textContent+=(document.getElementById('builderAnswer').textContent?' ':'')+w}
function nextBuilder(){const s=state();s.builderDone++;save(s);window.builder.i=(window.builder.i+1)%builderData.length;updateBuilder()}
function initJournal(){document.getElementById('date').value=today(); renderEntries()}
function saveJournal(){const t=document.getElementById('text').value.trim(); if(!t)return; const s=state(); s.journals.unshift({date:document.getElementById('date').value,text:t}); if(!s.studyDays.includes(today()))s.studyDays.push(today()); const words=t.toLowerCase().match(/[a-z]+/g)||[]; s.learnedWords=[...new Set([...s.learnedWords,...words.filter(w=>w.length>=5)])]; save(s); document.getElementById('saved').textContent='Saved. Your next quiz will use this journal.'; renderEntries()}
function renderEntries(){const s=state();document.getElementById('entries').innerHTML=s.journals.slice(0,5).map(j=>`<div class="card"><small>${j.date}</small><p>${esc(j.text)}</p></div>`).join('')}
function initQuiz(){const s=state(), review=new URLSearchParams(location.search).get('review'); if(review)document.getElementById('quizTitle').textContent=`${review}-Day Review`; const qs=[]; lessons.forEach(l=>l.questions.forEach(q=>qs.push({q:q[0],opts:q[1],a:q[2],topic:l.title}))); const recent=s.mistakes.slice(0,3).map(m=>({q:`Which correction is correct? ${m.question}`,opts:[m.answer,m.user,'Neither'],a:m.answer,topic:'Mistake review'})); const all=[...recent,...qs].sort(()=>Math.random()-.5).slice(0,5); let score=0, answered=0; document.getElementById('quiz').innerHTML=all.map((q,i)=>`<div class="card quiz-q"><small>${esc(q.topic)}</small><h3>${i+1}. ${esc(q.q)}</h3>${q.opts.map(o=>`<button class="btn option" data-i="${i}" data-a="${esc(q.a)}" onclick="answerQuiz(this,'${esc(o)}','${esc(q.a)}','${esc(q.q)}')">${esc(o)}</button>`).join('')}<p id="fb${i}"></p></div>`).join('')+`<div class="card"><p id="result">Answer all questions.</p></div>`; window.quiz={score,answered,total:all.length}}
function answerQuiz(btn,user,correct,q){if(btn.parentElement.dataset.done)return;btn.parentElement.dataset.done='1';window.quiz.answered++; const ok=user===correct; if(ok)window.quiz.score++; else{const s=state();s.mistakes.unshift({date:today(),question:q,user,answer:correct});save(s)} btn.parentElement.querySelector('p').textContent=ok?'Correct!':'Correct answer: '+correct; if(window.quiz.answered===window.quiz.total){const s=state();const pct=Math.round(window.quiz.score/window.quiz.total*100);s.quizHistory.push({date:today(),score:pct});if(!s.studyDays.includes(today()))s.studyDays.push(today());save(s);document.getElementById('result').innerHTML=`<span class="result">${pct}%</span><br>Score saved. ${pct>=80?'Great recall!':'Review your mistakes and try again tomorrow.'}`}}
function renderMistakes(){const s=state();document.getElementById('mistakes').innerHTML=s.mistakes.length?s.mistakes.slice(0,50).map(m=>`<div class="mistake"><small>${m.date}</small><div><b>${esc(m.question)}</b></div><div>Your answer: ${esc(m.user)}</div><div>Correct: <b>${esc(m.answer)}</b></div></div>`).join(''):'<div class="card">No mistakes yet. Your quiz mistakes will appear here automatically.</div>'}
function renderProgress(){const s=state(), h=s.quizHistory;document.getElementById('improve').textContent=Math.min(30,s.studyDays.length)+'%';document.getElementById('avg').textContent=h.length?Math.round(h.reduce((a,x)=>a+x.score,0)/h.length)+'%':'0%';document.getElementById('days').textContent=s.studyDays.length;document.getElementById('words').textContent=s.learnedWords.length;document.getElementById('chart').innerHTML=Array.from({length:30},(_,i)=>{const v=Math.min(100,(s.studyDays.length>i?Math.max(8,(i+1)*3):4));return `<div class="bar" style="height:${v}%"></div>`}).join('')}
function initSettings(){const s=state();document.getElementById('provider').value=s.settings.provider;document.getElementById('endpoint').value=s.settings.endpoint}
function saveSettings(){const s=state();s.settings={provider:document.getElementById('provider').value,endpoint:document.getElementById('endpoint').value};save(s);document.getElementById('status').textContent='Settings saved.'}
